### ISSUE TITLE
Update project description

### ISSUE THREAD

**Issue by olejandro** [etsap-TIMES/xl2times#113]
> This project is an open source tool to convert TIMES model Excel input files to DD format ready for processing by GAMS. The intention is to make it easier for people to reproduce research results on TIMES models.

These statements ignore the **existence** of Veda - it is **subsumed** in TIMES. I just want to ensure that developers and users of this project are aware that Veda and TIMES are separate entities.

"TIMES model input files" are the DD files. The Excel files you are refering to are **Veda input files**. These Excel files contain an original syntax that introduced a new way of **creating** data - via rule-based processing of flexible formats. For example, the ability to identify nodes of a RES based on set membership, name, description, and topology and add/edit parameters - is Veda. This has absolutely nothing to do with TIMES. The project is replicating this ability using different software tools, without mentioning "Veda" anywhere, which implicitly makes all the data concepts of Veda a part of TIMES.

_Originally posted by @akanudia in https://github.com/etsap-TIMES/times-excel-reader/issues/109#issuecomment-1702094757_

**Comment by akanudia** [comment]
This project is an open-source tool to convert [Veda](https://veda-documentation.readthedocs.io/en/latest/) (a proprietary data handling system developed by KanORS) input files to TIMES DD format ready for processing by GAMS. The intention is to make it easier for people to reproduce research results from TIMES models that may have been generated using proprietary tools. While the project is starting with Veda syntax, we envision that it will eventually go beyond the methods and formats introduced by Veda.

**Comment by evelynwright** [comment]
Thanks for starting the new thread @olejandro . What @akanudia 's written sounds -- from what I understand of the project -- like an accurate depiction of both the starting points and the project goals. 

I think the clarification is helpful. The tool will not be able to read ANSWER TIMES input files, or any other Excel TIMES input format that someone might have developed for their own use, right? Only VEDA? 

It makes sense to limit the effort to reading VEDA input files, because the user who wants to replicate research is increasingly unlikely to encounter an ANSWER-based model, although several are still in use, I believe. But it should be clarified in the description. 

Does what Amit has added about the project goals accurately reflect how you see it?

**Comment by olejandro** [comment]
Thanks for joining the discussion @evelynwright. As such the tool is open for any other TIMES model format specification (also non-excel). Unfortunately we have barely updated the readme, since forking the original Microsoft repository. Apologies for that. If you are interested, I can also share the ETSAP project proposal with you.

**Comment by olejandro** [comment]
@akanudia thank you once again for engaging on this. I've opened #202 to address the issue. Here is the [README](https://github.com/etsap-TIMES/xl2times/blob/olex/clean-up/README.md) with proposed changes. I would appreciate any further feedback from you on this.
